version: '3'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-release:1.0.0
    env_file: .env
    restart: always
    ports: 
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-release:1.0.0
    restart: always
    ports:
      - '8081:80'
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - postgres_data_pub:/data/postgres
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data_pub:

networks:
  backend:
  frontend:
