version: '3'

services:
  backend:
    container_name: backend
    image: vierim/backend-release:1.0.0
    env_file: .env
    restart: always
    ports: 
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    image: vierim/frontend-release:1.0.1
    restart: always
    ports:
      - '8081:80'
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    restart: always
    volumes:
      - postgres_data_pub:/data/postgres
    networks:
      - backend

volumes:
  postgres_data_pub:

networks:
  backend:
  frontend:
